image: mrcyjanek/goprod:linux-core
script:
  - checkinstall --requires=chafa --type=debian --install=no --default --pkgname=shell-greet --pkgversion=0.0.0+git$(git show -s --date=format:%Y%m%d%H%M --format=%cd) --arch=all --pakdir=build/deb --maintainer=cyjan@mrcyjanek.net --strip=no --stripso=no